version: '2'

services:

  mongodb:
    image: mongo:6-jammy
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

  app:
    image: 'example/mongocrud:latest'
    build:
      context: .
    container_name: mongocrud-app
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_container:27017/trading
    ports:
      - "8080:8080"
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge